:sparkles: evolutions
Zenika/coffee-button pull request #25
Opened 2019-12-05 16:19 UTC by yodur2potassium

As described in #23, this PR intends to implements a few improvements on the V1:
 - a `dry-run` option to retrieve the last logs and update source code
 - a `keep-running` option to easily debug the button by preventing it to shutdown after use
 - clearer logs & few changes proposed by `shellcheck`

2019-12-08 09:16 UTC, louckousse approved these changes

2019-12-09 09:46 UTC, yodur2potassium commented
@louckousse ❤️

2019-12-09 09:53 UTC, gmembre-zenika requested changes

2019-12-09 09:53 UTC, gmembre-zenika commented on init.sh
> +CURRENT_DATE=$(gdate +"%F-%H:%M")
`gdate` existe sous linux ? c'est pour mac en général pour combler les lacunes...

2019-12-09 09:53 UTC, gmembre-zenika commented on init.sh
> +git pull origin master
C'est étrange de faire un `git pull` *après* l'utilisation des scripts

2019-12-09 09:56 UTC, yodur2potassium commented on init.sh
> +CURRENT_DATE=$(gdate +"%F-%H:%M")
Argh, l'oubli fatal... Merci Guillaume!

2019-12-09 09:59 UTC, yodur2potassium commented on init.sh
> +git pull origin master
Si je ne dis pas de bêtise, une fois le script lancé c'est le code de celui-ci qui sera exécuté, non? La mise à jour du code source se ferait par un démarrage en `DRY_RUN`

2019-12-09 10:08 UTC, gmembre-zenika commented on init.sh
> +git pull origin master
je ne comprends pas : lorsque le pi démarre, il exécute le `init.sh` non ? Dans ce script, différents fichiers sont récupérés et notamment le `curl` est exécuté.
Si le script est mis à jour à la fin, les évolutions ne seront prise en compte qu'au 2e démarrage du pi, non ?

2019-12-09 10:31 UTC, yodur2potassium commented on init.sh
> +git pull origin master
En effet, pour l'instant il faut attendre le deuxième démarrage pour avoir la version à jour du code source.

2019-12-10 09:29 UTC, yodur2potassium commented on init.sh
> +git pull origin master
Ok je bascule dans un premier temps sur un `DRY_RUN`par défaut et une modif du fichier d'env après le premier run. L'idée c'est de faire la mise à jour des sources et d’empêcher de commander lors du branchement après debug...

2019-12-10 16:48 UTC, merged